name: CI Pipeline
on:
push:
branches:
- main
jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout Code
uses: actions/checkout@v2
- name: Build Application
run: echo "Building the application..."
test:
runs-on: ubuntu-latest
steps:
- name: Run Tests
run: echo "Running tests... All tests passed!"
deploy:
runs-on: ubuntu-latest
steps:
- name: Deploy Application
run: echo "Deploying application..."
